### PR TITLE
Supporting IPv6 dns servers

### PR DESCRIPTION
**Pull request by oxtoacart**

### CODE REVIEW

**Comment by atavism** [comment]
LGTM, @oxtoacart. Maybe one other thing we could do is just add a new test for IPv6?

**Comment by oxtoacart** [comment]
> Maybe one other thing we could do is just add a new test for IPv6?

Sorry about the slow reply. I like the idea in principle, but it's not clear to me whether we can construct such a test that will work on systems running on networks that don't support IPv6 ...

**Comment by atavism** [comment]
@oxtoacart Understood. I initially just meant a test to verify protected is configurable using an IPv6  address (without testing connectivity). But is there a way to check if the network is IPv6 compatible and, if so, try doing the resolution via Google's IPv6 public DNS server? `2001:4860:4860::8888` for instance

**Comment by oxtoacart** [comment]
> But is there a way to check if the network is IPv6 compatible and, if so, try doing the resolution via Google's IPv6 public DNS server? 2001:4860:4860::8888 for instance

I like that, implementing now.

**Comment by oxtoacart** [comment]
Okay test is added, found some bugs and fixed them, seems to be working fine on my Android.

**Comment by atavism** [comment]
Ah, awesome! Glad we decided to add that test then. This is working well for me too. Merging!

**Pull request merged**
