### PR TITLE
fleshed out log

### PR DESCRIPTION
**Pull request by myleshorton**

### CODE REVIEW

**Comment by myleshorton** [comment]
Just a tiny log change if you want to take a look @oxtoacart or @joesis

**Comment by oxtoacart** [comment]
@myleshorton My only comment is that the socket type is just going to be an integer, which won't be super useful to whoever is reading it. At the place where we set the socket type, we could also set a human readable description which we then use in the error message.

**Comment by myleshorton** [comment]
Yup I'll make that change @oxtoacart thanks!

**Comment by myleshorton** [comment]
I ended up just using the `network` instead of `socketType` @oxtoacart

**Comment by atavism** [comment]
LGTM

**Pull request merged**
